export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Products } from './Products'
export { default as Categories } from './Categories'
export { default as Banners } from './Banners'
export { default as Pages } from './Pages'
export { default as Settings } from './Settings'
